package org.matrix.vector.manager.data.repository

import org.matrix.vector.manager.data.github.ClosedIssue
import org.matrix.vector.manager.data.github.CommunityFeed
import org.matrix.vector.manager.data.github.FrameworkRelease
import org.matrix.vector.manager.data.github.TimelineCommit

/**
 * What the canary list draws, in order.
 *
 * **A version code is a commit count.** `versionCode` is generated by `git rev-list --count`, and
 * `TimelineCommit.globalIndex` counts the same way on the same history, so the commits a build
 * carries over the one before it are not an estimate — they are the half-open range between two
 * version codes, and the feed the home screen already holds can name them.
 *
 * That is the whole reason this file exists. Without it a canary row can only say what it is
 * called and how big its zip is, which tells a reader nothing about whether it is worth their
 * evening. With it the row says what landed, and the page above it says what has been fixed since
 * the build they are running.
 */
sealed interface CanaryItem {

    /** One published canary, with the work it brought over the canary below it. */
    data class Build(val span: CanarySpan) : CanaryItem

    /**
     * Where the reader's own build sits among the canaries.
     *
     * The same marker the commit rail draws, for the same reason and from the same numbers:
     * everything above it is what installing would actually bring.
     */
    data class Installed(
        val versionCode: Long,
        val commitsAhead: Int,
        /** Running something newer than every published canary — a local or branch build. */
        val ahead: Boolean,
    ) : CanaryItem
}

/**
 * One canary: the build, and the commit it was cut from.
 *
 * **The head commit, and nothing else about the history.** A build is one commit — the tip CI
 * happened to build — and that commit's subject is what tells a reader what this build is. Counting
 * the commits between it and the build below says only how much time passed, which the dates
 * already say, and it competed for room with the thing worth reading.
 */
data class CanarySpan(
    val release: FrameworkRelease,
    /**
     * The commit this build was made from, when the feed reaches it.
     *
     * Matched by SHA rather than by version code. Both would usually work, but `globalIndex` is
     * assigned by counting down from a total across a paged fetch, and its own documentation warns
     * that a page lost after it was written leaves the numbers below the seam reading high. A
     * release names its commit exactly, so there is no reason to rely on the fragile one.
     */
    val head: TimelineCommit?,
    /**
     * The subject to show, from the head commit or, failing that, from the release notes.
     *
     * CI writes the commit subject as the first bold line of every canary's notes, so a build whose
     * commit the feed no longer reaches — older than the window, or a cold cache — still has a
     * title rather than a bare number.
     */
    val subject: String?,
    /** True when this is the build that is running. */
    val installed: Boolean,
    /** True when the running build wears this number but was not built from this release. */
    val diverged: Boolean,
)

/**
 * The sentence at the top of the canary screen: what taking one would get this reader.
 *
 * [fixed] is the recruiting number, and it is a claim about other people's reports rather than
 * about our own commit subjects — which is what makes it worth stating. It is scoped by time, not
 * by authorship: these are the issues closed as done *since the reader's build was cut*, which is
 * the only attribution obtainable without an account. That the sentence says exactly that, and
 * claims no more, is deliberate.
 */
data class CanaryOverview(
    val installedVersionCode: Long,
    val commitsAhead: Int,
    /** Issues closed as completed since the running build, newest first. */
    val fixed: List<ClosedIssue> = emptyList(),
    /** True when the running build is itself a canary: this reader is already testing. */
    val onCanary: Boolean = false,
    /** True when the running build is newer than every published canary. */
    val ahead: Boolean = false,
    /**
     * True when the running build carries a listed canary's number but was not built from it.
     *
     * A version code is a commit count, not an identity: a build from another branch, or from a
     * working tree with changes in it, reaches the same count and wears the same number. Without
     * this the page would tell such a reader they were running the newest canary while the card for
     * that canary, two lines below, marked itself "same number, other build".
     */
    val diverged: Boolean = false,
) {
    val behind: Boolean
        get() = commitsAhead > 0
}

data class CanaryBoard(
    val overview: CanaryOverview = CanaryOverview(0, 0),
    val items: List<CanaryItem> = emptyList(),
    /** False until the release list has answered; the screen spins rather than saying "none". */
    val loaded: Boolean = false,
)

object CanaryLayout {

    /**
     * @param attempted whether the release list has been asked for and answered, however it
     *   answered. A refusal — no network, a rate limit, a daemon that cannot say what is installed
     *   — leaves the catalogue empty, and without this the screen could not tell that from a fetch
     *   still in flight, so it span forever on exactly the devices least able to reach GitHub.
     */
    fun build(
        feed: CommunityFeed,
        state: FrameworkUpdateState,
        closed: List<ClosedIssue>,
        attempted: Boolean,
    ): CanaryBoard {
        val canaries = state.catalog.filter { it.isCanary }.sortedByDescending { it.versionCode }
        val installed = state.installedVersionCode
        val loaded = attempted || state.catalog.isNotEmpty()
        if (canaries.isEmpty()) return CanaryBoard(loaded = loaded, items = emptyList())

        val newest = canaries.first().versionCode
        val since = state.builtAt(feed)
        val overview =
            CanaryOverview(
                installedVersionCode = installed,
                commitsAhead = (newest - installed).coerceAtLeast(0).toInt(),
                fixed =
                    if (since == null) emptyList()
                    else closed.filter { it.closedAtEpoch > since },
                onCanary = state.onCanary,
                ahead = installed > newest,
                diverged =
                    canaries
                        .firstOrNull { it.versionCode == installed }
                        ?.let { state.divergesFrom(it) } == true,
            )

        val items = ArrayList<CanaryItem>(canaries.size + 1)
        // Above every canary, because there is no canary it could sit under. A build past the head
        // of master is not a position in this list; it is a statement that the list does not
        // describe what is running.
        if (overview.ahead) {
            items += CanaryItem.Installed(installed, overview.commitsAhead, ahead = true)
        }
        // Nothing to mark when the reader is already on the newest canary: the card for it is
        // badged as installed, and a marker under it saying "0 commits newer than yours" is a
        // sentence about nothing.
        var markerPlaced = overview.ahead || installed <= 0 || !overview.behind

        canaries.forEachIndexed { index, release ->
            val head = release.commit?.let { sha -> feed.commits.firstOrNull { it.sha == sha } }

            items +=
                CanaryItem.Build(
                    CanarySpan(
                        release = release,
                        head = head,
                        subject = head?.subject ?: release.notesSubject(),
                        installed = release.versionCode == installed,
                        diverged = state.divergesFrom(release),
                    )
                )

            // Placed under the last canary that is newer than the reader's build, which is where
            // the line between "what I could have" and "what I already have" actually falls.
            val next = canaries.getOrNull(index + 1)
            if (!markerPlaced && (next == null || next.versionCode <= installed)) {
                items += CanaryItem.Installed(installed, overview.commitsAhead, ahead = false)
                markerPlaced = true
            }
        }

        return CanaryBoard(overview = overview, items = items, loaded = true)
    }
}

/**
 * When the running build was cut, or null when that cannot be established.
 *
 * The commit at the reader's version code is the exact answer and needs no extra request — the
 * version code *is* that commit's position. A published build the feed no longer reaches falls
 * back to when its release went out, which is within hours of the same thing. A build that is
 * neither in the window nor in the catalogue — someone's own — has no date here, and the screen
 * says nothing about what has been fixed rather than guessing a span.
 */
private fun FrameworkUpdateState.builtAt(feed: CommunityFeed): Long? =
    feed.commits.firstOrNull { it.globalIndex == installedVersionCode }?.epochSeconds
        ?: catalog.firstOrNull { it.versionCode == installedVersionCode }?.epochSeconds

/**
 * The commit subject CI wrote into the release notes, or null.
 *
 * The workflow opens every canary's body with the subject in bold — `**Keep a module inside the
 * users that installed it**` — so this is a copy of the same string the commit carries, published
 * alongside the zips. It is the fallback for a build the commit feed cannot reach, and it is why
 * such a build still reads as a build rather than as a number.
 */
private fun FrameworkRelease.notesSubject(): String? =
    notesMarkdown
        ?.lineSequence()
        ?.firstOrNull { it.isNotBlank() }
        ?.trim()
        ?.let { NOTES_SUBJECT.find(it)?.groupValues?.getOrNull(1) }
        ?.takeIf { it.isNotBlank() }

private val NOTES_SUBJECT = Regex("""^\*\*(.+?)\*\*$""")
