package org.matrix.vector.manager.data.github

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The slice of GitHub's commit payload the Home feed needs.
 *
 * One request to `/commits?since=…` carries everything: the author's login and avatar for the
 * contributor row, the date for the timeline, the subject line, and the SHA. There is deliberately
 * no second call to `/contributors` — the people are derived from the commits, which both halves
 * the rate-limit spend and makes the row mean "who worked on this *recently*" rather than an
 * all-time leaderboard nobody reads twice.
 */
@Serializable
data class GhCommit(
    val sha: String,
    val commit: GhCommitDetail,
    val author: GhUser? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
)

@Serializable
data class GhCommitDetail(
    val message: String,
    val author: GhCommitAuthor,
    /**
     * When the commit landed, as opposed to when it was written.
     *
     * The two differ on about half of the newest hundred commits here, by as much as three weeks —
     * anything rebased, cherry-picked or merged from a branch that sat for a while. It matters
     * because `since` and `until` filter on *this* date, so it is the only correct cursor for
     * walking history backwards. Walking on the author date would step past commits written before
     * the boundary but landed after it, and lose them silently.
     */
    val committer: GhCommitAuthor? = null,
)

@Serializable
data class GhCommitAuthor(
    val name: String,
    val date: String,
    /** Present on every commit, and the only handle on an author GitHub failed to link. */
    val email: String = "",
)

@Serializable
data class GhUser(
    val login: String,
    @SerialName("avatar_url") val avatarUrl: String? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
    val type: String? = null,
)

@Serializable
data class GhRepo(
    @SerialName("stargazers_count") val stars: Int = 0,
    @SerialName("forks_count") val forks: Int = 0,
    @SerialName("open_issues_count") val openIssues: Int = 0,
    val license: GhLicense? = null,
)

@Serializable data class GhLicense(@SerialName("spdx_id") val spdxId: String? = null)

/**
 * How a commit subject is classified.
 *
 * Vector writes plain imperative subjects rather than conventional-commit prefixes, so the leading
 * verb is what gets read. Over the newest 300 commits that verb is a fix or a dependency bump
 * almost half the time, which is why those two have categories of their own.
 */
enum class CommitKind {
    Fix,
    Add,
    Remove,
    Chore,
    Change;

    companion object {
        fun of(subject: String): CommitKind =
            when (subject.substringBefore(' ').trimStart('[').lowercase()) {
                "fix",
                "fixes",
                "fixed" -> Fix
                "add",
                "adds",
                "new",
                "implement",
                "introduce",
                "allow",
                "support" -> Add
                "remove",
                "removes",
                "delete",
                "drop" -> Remove
                "bump",
                "update",
                "upgrade",
                "migrate",
                "translation]",
                "translation" -> Chore
                else -> Change
            }
    }
}

/**
 * One person credited on a commit — the author, or anyone named in a `Co-authored-by:` trailer.
 *
 * Co-authors are real contributors and are counted as such. GitHub's commits API does not return
 * them as users, so they are parsed out of the message; when the trailer carries a GitHub noreply
 * address the login and avatar can be recovered from it exactly, and otherwise the person is shown
 * under the name they signed with and a monogram.
 */
data class CommitPerson(
    val login: String,
    val avatarUrl: String?,
    val profileUrl: String?,
    val isBot: Boolean = false,
)

/** A commit as the timeline renders it. */
data class TimelineCommit(
    val sha: String,
    val shortSha: String,
    val subject: String,
    val kind: CommitKind,
    /** Pull-request number parsed from a trailing `(#123)`, the link to the discussion. */
    val pullRequest: Int?,
    /** The author first, then any co-authors, deduplicated. */
    val authors: List<CommitPerson>,
    val epochSeconds: Long,
    val htmlUrl: String?,
    /**
     * Distance from the repository's first commit, i.e. this commit's own version number —
     * `versionCode` is generated by `git rev-list --count`, so the two are the same scale and a
     * build can be located on the timeline exactly.
     */
    val globalIndex: Long,
    /** True when anyone credited, bots aside, is not the repository owner — marked on the rail. */
    val isCommunity: Boolean,
    val isBot: Boolean,
) {
    val authorLogin: String
        get() = authors.firstOrNull()?.login.orEmpty()

    val coAuthors: List<CommitPerson>
        get() = authors.drop(1)
}

/** A person credited inside the window, with how much and how recently. */
data class Contributor(
    val login: String,
    val avatarUrl: String?,
    val profileUrl: String?,
    val commits: Int,
    /** Their most recent commit in the window; breaks ties so the row stays a live scoreboard. */
    val lastEpochSeconds: Long,
)

/** Everything the Home community section renders, or the reason it cannot. */
data class CommunityFeed(
    val commits: List<TimelineCommit> = emptyList(),
    val contributors: List<Contributor> = emptyList(),
    val windowStartEpochSeconds: Long = 0,
    val repo: GhRepo? = null,
    /** Commits on the default branch, ever. Equals the newest build's versionCode. */
    val totalCommits: Long = 0,
    /** True when this came off disk rather than the network, for any reason. */
    val fromCache: Boolean = false,
    /**
     * True only when the network was actually tried and could not be reached.
     *
     * Not the same as [fromCache]. Home deliberately reads the cache on most launches, so "could
     * not reach GitHub" keyed off [fromCache] would report a failure on a launch that never asked.
     */
    val offline: Boolean = false,
    /**
     * False until the first load resolves. Without it the initial empty value is indistinguishable
     * from a genuinely empty result, and the page claims "no commits" before it has looked.
     */
    val loaded: Boolean = false,
    /**
     * True while the archive has not yet been walked back as far as this window reaches.
     *
     * The distinction the feed's foot depends on: more to fetch means an invitation to keep
     * scrolling, nothing more to fetch means the rail has genuinely reached the first commit and
     * says so.
     */
    val hasMoreHistory: Boolean = false,
    /**
     * True when a bounded window is already backed by history reaching past its start.
     *
     * The distinction the foot of the feed needs: "there is nothing more *here*" is a different
     * sentence from "this is where the project began", and neither is "there is more to fetch".
     */
    val windowCovered: Boolean = false,
) {
    val commitCount: Int
        get() = commits.size

    val isEmpty: Boolean
        get() = commits.isEmpty()

    /**
     * The same feed narrowed to the commits [logins] took part in.
     *
     * Co-authorship counts, which is the whole point of filtering here rather than linking out to
     * GitHub's author filter: GitHub's own view is by *author*, so a contribution that landed under
     * a maintainer's name with the contributor credited in a trailer does not appear under the
     * contributor at all. Here it does, because the rail already knows every name on a commit.
     *
     * Only the commits are narrowed. The contributor row is the control — filtering it by its own
     * selection would remove the people you would need to tap to change it.
     */
    fun filteredBy(logins: Set<String>): CommunityFeed =
        if (logins.isEmpty()) this
        else
            copy(
                commits =
                    commits.filter { commit ->
                        commit.authors.any { it.login.lowercase() in logins }
                    }
            )
}

// --- CI builds ------------------------------------------------------------------------------

@Serializable
data class GhRelease(
    val id: Long,
    @SerialName("tag_name") val tagName: String = "",
    val name: String? = null,
    val prerelease: Boolean = false,
    @SerialName("target_commitish") val targetCommitish: String = "",
    @SerialName("published_at") val publishedAt: String? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
    val body: String? = null,
    val assets: List<GhReleaseAsset> = emptyList(),
)

@Serializable
data class GhReleaseAsset(
    val id: Long,
    val name: String,
    val size: Long = 0,
    @SerialName("browser_download_url") val downloadUrl: String? = null,
)

/**
 * A closed issue, as GitHub's issue list reports it.
 *
 * **This is how the canary screen knows what got fixed, and it has to be.** A commit message only
 * names an issue when somebody wrote `Fixes #816` into it; this repository's issues are usually
 * linked through the web UI's *Development* panel instead, which closes them on merge and writes
 * nothing into the history at all. The link itself is only readable through GraphQL —
 * `PullRequest.closingIssuesReferences` — and GraphQL answers 403 to an anonymous caller, which
 * this app is by design. So what is asked instead is the question REST will answer without an
 * account: which issues closed, and when.
 */
data class ClosedIssue(
    val number: Int,
    val title: String,
    val closedAtEpoch: Long,
    val htmlUrl: String?,
)

@Serializable
data class GhIssue(
    val number: Int,
    val title: String = "",
    @SerialName("closed_at") val closedAt: String? = null,
    /**
     * Why it closed: `completed`, `not_planned` or `duplicate`.
     *
     * Only the first is a fix. Counting the others would tell a reader that eleven issues were
     * dealt with since their build when five of them were triage.
     */
    @SerialName("state_reason") val stateReason: String? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
) {
    /**
     * Whether this is really a pull request.
     *
     * The issues endpoint returns both — a pull request *is* an issue to GitHub — and in one page
     * of this repository's closed items more than half were pull requests. Told apart by the URL
     * rather than by the presence of the `pull_request` object, which would mean decoding a nested
     * payload none of whose fields are wanted.
     */
    val isPullRequest: Boolean
        get() = htmlUrl?.contains("/pull/") == true
}

/**
 * A published build of the framework, canary or stable, with the zip to flash.
 *
 * One type for both channels because the install path is identical — the difference is only which
 * of them a given reader is allowed to be offered.
 *
 * One type for the canary list as well, which used to read the same endpoint through a shape of its
 * own. Two models over one response meant the canary page fetched what the update page was already
 * holding, and could say nothing about a build that this type does not carry — no notes, no commit,
 * and so no way to mark the one that is running.
 */
data class FrameworkRelease(
    val tag: String,
    val title: String,
    val versionCode: Long,
    val isCanary: Boolean,
    val notesMarkdown: String?,
    val htmlUrl: String?,
    val epochSeconds: Long,
    /**
     * The commit the release was cut from, when GitHub knows one.
     *
     * `target_commitish` is a full SHA for the canaries, because CI creates them against an exact
     * commit — but it is the literal string "master" for a hand-made release, which names a branch
     * and not a build. Only the first kind can be compared against, and the difference between
     * "these differ" and "I cannot tell" is one the UI has to keep.
     */
    val commit: String?,
    /**
     * Every zip the release published, in the order GitHub listed them.
     *
     * A list rather than one chosen zip because each release ships both a Release and a Debug
     * build, and they are very different sizes. The reader has to be able to see which one they
     * are about to flash and to pick the other — the app asks people for a debug build when they
     * report a problem, so installing one has to be possible.
     */
    val zips: List<CanaryArtifact>,
) {
    /** The one to offer by default when nothing has been chosen. */
    val defaultZip: CanaryArtifact?
        get() = zips.firstOrNull { it.variant == ZipVariant.Release } ?: zips.firstOrNull()

    /**
     * The commit, abbreviated the way git abbreviates it, or null when the release names a branch.
     *
     * Seven characters because that is what `git rev-parse --short` gives on a repository this
     * size, and what the commit rail already prints — the two are read side by side.
     */
    val shortSha: String?
        get() = commit?.take(7)
}

/**
 * Which build a zip is, read from its file name.
 *
 * [Other] is not a failure: a release may one day publish something these two names do not cover,
 * and a picker that cannot represent it would either hide the file or mislabel it. Both are worse
 * than showing the name it actually has.
 */
enum class ZipVariant(val key: String) {
    Release("release"),
    Debug("debug"),
    Other("other"),
}

data class CanaryArtifact(
    val id: Long,
    val name: String,
    val sizeInBytes: Long,
    val downloadUrl: String?,
) {
    val variant: ZipVariant
        get() =
            when {
                name.contains("release", ignoreCase = true) -> ZipVariant.Release
                name.contains("debug", ignoreCase = true) -> ZipVariant.Debug
                else -> ZipVariant.Other
            }
}

